{{- if eq .chezmoi.os "windows" }}

# nushell configuration for Windows
["AppData/Roaming/nushell/config.nu"]
    type = "file"
    url = "file://{{ .chezmoi.sourceDir }}/dot_config/nushell/config.nu"

["AppData/Roaming/nushell/env.nu"]
    type = "file"
    url = "file://{{ .chezmoi.sourceDir }}/dot_config/nushell/env.nu"

# alacritty configuration for Windows
["AppData/Roaming/alacritty/alacritty.toml"]
    type = "file"
    url = "file://{{ .chezmoi.sourceDir }}/dot_config/alacritty/alacritty.toml"

# zellij configuration for Windows
["AppData/Roaming/Zellij/config.kdl"]
    type = "file"
    url = "file://{{ .chezmoi.sourceDir }}/dot_config/zellij/config.kdl"

# zellij configuration for Windows
["AppData/Roaming/Zellij/config/config.kdl"]
    type = "file"
    url = "file://{{ .chezmoi.sourceDir }}/dot_config/zellij/config.kdl"

{{- end }}
