[Hotkey/TriggerKeys]
0=Control+space

[Hotkey/AltTriggerKeys]
0=

[Hotkey/ToggleHotkeys]
0=

[Hotkey/EnumerateForwardKeys]
0=

[Hotkey/EnumerateBackwardKeys]
0=

[Hotkey/EnumerateGroupForwardKeys]
0=

[Hotkey/EnumerateGroupBackwardKeys]
0=
