[Hotkey/TriggerKeys]
0=Control+space

[Hotkey/AltTriggerKeys]
0=

[Hotkey/ToggleHotkeys]
0=

[Hotkey/EnumerateForwardKeys]
0=

[Hotkey/EnumerateBackwardKeys]
0=

[Hotkey/EnumerateGroupForwardKeys]
0=

[Hotkey/EnumerateGroupBackwardKeys]
0=

[Hotkey/TriggerKeyOnlyWhenEmpty]
True=False

[Hotkey/UseCustomSortToggle]
0=False

[Hotkey/ShowInputMethodInformation]
0=False
1=False
2=False

[Hotkey/SwitchEmbeddedPreedit]
0=
